
CREATE TABLE FunctionDetails (
    ID INT PRIMARY KEY,
    ID_Depth_Level INT NOT NULL,
    Category VARCHAR(255) NOT NULL,
    User_Behavior_Analysis TEXT,
    Optimization_Potential TEXT,
    Potential_Extensions TEXT,
    Usage_Statistics TEXT,
    Related_Functions TEXT,
    Process_Flow TEXT,
    UIX_Score FLOAT,
    Priority_Level VARCHAR(50),
    Monetization_Value DECIMAL(10, 2),
    Associated_Chart TEXT,
    Integration_Notes TEXT,
    Personalization_Options TEXT
);

INSERT INTO FunctionDetails (
    ID, ID_Depth_Level, Category, User_Behavior_Analysis, Optimization_Potential, 
    Potential_Extensions, Usage_Statistics, Related_Functions, Process_Flow, 
    UIX_Score, Priority_Level, Monetization_Value, Associated_Chart, Integration_Notes, 
    Personalization_Options
) VALUES (
    1, 
    1, 
    'Rejestracja i Logowanie', 
    'Użytkownik chce szybko zalogować się do aplikacji, szczególnie przy dużym obciążeniu serwerów. Intencja: uproszczenie procesu logowania. Sytuacja: użytkownik korzysta z funkcji "Zapamiętaj mnie".', 
    'Skrócenie czasu odpowiedzi serwera logowania. Dodanie opcji biometrycznego uwierzytelniania.', 
    'Integracja z systemem logowania Facebook. Rozbudowa weryfikacji dwuetapowej.', 
    'Liczba logowań dziennie: 1000. Najczęściej wykorzystywana funkcja w godzinach 18:00-21:00.', 
    '$1.1.2 (Rejestracja za pomocą mediów społecznościowych)', 
    'Wprowadzenie email i hasła. Weryfikacja użytkownika. Przekierowanie na ekran główny.', 
    9.5, 
    'Wysoki priorytet (1)', 
    5000.00, 
    'Wykres: Słupkowy przedstawiający popularność funkcji w zależności od pory dnia.', 
    'Aktualnie wspiera OAuth dla Google. Planowana integracja z Apple ID.', 
    'Wybór ciemnego lub jasnego motywu. Funkcja "Zapamiętaj mnie".'
);

INSERT INTO FunctionDetails (
    ID, ID_Depth_Level, Category, User_Behavior_Analysis, Optimization_Potential, 
    Potential_Extensions, Usage_Statistics, Related_Functions, Process_Flow, 
    UIX_Score, Priority_Level, Monetization_Value, Associated_Chart, Integration_Notes, 
    Personalization_Options
) VALUES
(2, 1, 'Powiadomienia', 
 'Użytkownik chce być informowany o nowych wiadomościach.', 
 'Optymalizacja mechanizmu powiadomień push.', 
 'Integracja z systemem kalendarzy.', 
 'Średnio 200 powiadomień na użytkownika dziennie.', 
 'Powiązane z $1.2.1 (System wiadomości)', 
 'Powiadomienie -> Kliknięcie -> Przekierowanie.', 
 9.0, 
 'Średni priorytet (2)', 
 2000.00, 
 'Wykres: Linia przedstawiająca liczbę powiadomień dziennie.', 
 'Obecnie wspiera tylko Android. Planowana integracja z iOS.', 
 'Wybór dźwięku powiadomień.'),
(3, 2, 'Wyszukiwanie', 
 'Użytkownik szuka konkretnych elementów w aplikacji.', 
 'Dodanie inteligentnych sugestii wyszukiwania.', 
 'Integracja z wyszukiwarką Elasticsearch.', 
 '1000 wyszukiwań na godzinę.', 
 'Powiązane z $2.1.1 (Rekomendacje).', 
 'Wpisanie frazy -> Wyświetlenie wyników.', 
 8.5, 
 'Wysoki priorytet (1)', 
 3500.00, 
 'Wykres: Histogram przedstawiający użycie funkcji w czasie.', 
 'Obecnie nie wspiera wyszukiwania głosowego.', 
 'Historia wyszukiwań użytkownika.'),
(4, 1, 'Płatności', 
 'Użytkownik realizuje płatność w aplikacji.', 
 'Usprawnienie mechanizmu zwrotów.', 
 'Integracja z nowymi systemami płatności.', 
 '500 transakcji dziennie.', 
 'Powiązane z $3.1.2 (Subskrypcje).', 
 'Wybór produktu -> Podanie danych płatności -> Finalizacja.', 
 9.8, 
 'Wysoki priorytet (1)', 
 15000.00, 
 'Wykres: Słupkowy przedstawiający transakcje w ciągu dnia.', 
 'Planowane rozszerzenie na kryptowaluty.', 
 'Zapamiętanie preferowanego sposobu płatności.'),
(5, 2, 'Obsługa klienta', 
 'Użytkownik zgłasza problem z aplikacją.', 
 'Skrócenie czasu odpowiedzi supportu.', 
 'Automatyczne odpowiedzi w chatbotach.', 
 '50 zgłoszeń na godzinę.', 
 'Powiązane z $4.2.1 (System ticketów).', 
 'Zgłoszenie -> Weryfikacja -> Odpowiedź.', 
 8.0, 
 'Średni priorytet (2)', 
 500.00, 
 'Wykres: Kołowy pokazujący podział zgłoszeń.', 
 'Obecnie brak integracji z CRM.', 
 'Możliwość dodania załączników w zgłoszeniu.'),
(6, 1, 'Profil użytkownika', 
 'Użytkownik edytuje swój profil.', 
 'Dodanie opcji zmian profilu w trybie offline.', 
 'Integracja z mediami społecznościowymi.', 
 '100 edycji dziennie.', 
 'Powiązane z $5.1.1 (Zdjęcia profilowe).', 
 'Otwórz profil -> Wprowadź zmiany -> Zapisz.', 
 8.9, 
 'Średni priorytet (2)', 
 1200.00, 
 'Wykres: Linia przedstawiająca zmiany profilu w czasie.', 
 'Planowana integracja z Dropbox.', 
 'Motywy graficzne dla profilu.');
