
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhhgaysawtaeimxeodfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoaGdheXNhd3RhZWlteGVvZGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODM0NjQsImV4cCI6MjA2NDY1OTQ2NH0.XvbFSKGO-3uYAEcFmHy6EzBHLGsOOerBO4mX9qwPc6Q";

// SECURITY: Service role key removed from frontend client
// Service role operations should only be performed in edge functions

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
